In [1]:
import numpy as np

In [ ]:
# Assignment 1
# Q1
#creating an array 
p = np.random.randint(1, 21, size = (5,5))
print(p)
print("2nd part of question")
# replacing the values of 3rd col to 1 
p[:,2]=1
print(p)

[[16 13 16 17  2]
 [19  9 20  4  3]
 [ 7  6 11  8  2]
 [19 14  6 14 17]
 [16  4 18 14  4]]
2nd part of question
[[16 13  1 17  2]
 [19  9  1  4  3]
 [ 7  6  1  8  2]
 [19 14  1 14 17]
 [16  4  1 14  4]]


In [ ]:
# Q2 
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr = np.arange(1,17).reshape(4,4)
for i in range(len(arr)):
    arr[i][i]=0
print(arr)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [11]:
# Assignment 2 
# Q1 
# Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
arr1 = np.arange(1,37).reshape(6,6)
print(arr1)
print(arr1[2:5,1:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [15]:
# Q2
# Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr2= np.random.randint(1,25,size =(5,5))
a = arr2[0,:]
b = arr2[-1,:]
c = arr2[:,0]
d = arr2[:,-1]
print(np.concatenate((a,b,c,d) ,axis=0))



[ 3  2  4 24 19 15 19 13 17 15  3  5 20  3 15 19  7  3 21 15]


In [16]:
# Assignment 3
# Q1
# Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
a = np.random.randint(1,10,size=(3,4))
b= np.random.randint(10,20,size=(3,4))
print("Array a:")
print(a)
print("Array b:")
print(b)
print("Element-wise addition:")
print(a+b)
print("Element-wise subtraction:")
print(a-b)
print("Element-wise multiplication:")
print(a*b)
print("Element-wise division:")
print(a/b)



Array a:
[[4 9 3 7]
 [6 6 2 6]
 [9 6 7 9]]
Array b:
[[16 19 12 15]
 [14 14 16 10]
 [10 19 10 10]]
Element-wise addition:
[[20 28 15 22]
 [20 20 18 16]
 [19 25 17 19]]
Element-wise subtraction:
[[-12 -10  -9  -8]
 [ -8  -8 -14  -4]
 [ -1 -13  -3  -1]]
Element-wise multiplication:
[[ 64 171  36 105]
 [ 84  84  32  60]
 [ 90 114  70  90]]
Element-wise division:
[[0.25       0.47368421 0.25       0.46666667]
 [0.42857143 0.42857143 0.125      0.6       ]
 [0.9        0.31578947 0.7        0.9       ]]


In [17]:
# Q2
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr3 = np.arange(1,17).reshape(4,4)
print("Array:")
print(arr3)
print("Row-wise sum:")
print(np.sum(arr3, axis=1))

print("Column-wise sum:")
print(np.sum(arr3, axis=0))

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


In [18]:
# Assignment 4
# Q1
# Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
e = np.random.randint(1,25,size =(5,5))
print("Array:")
print(e)
print(np.mean(e))
print(np.median(e))
print(np.std(e))

Array:
[[24 15 24 18 10]
 [15  1  7  4  8]
 [16  9 17 18  3]
 [19 17 16 16 20]
 [22  7  7 21  8]]
13.68
16.0
6.58920329023168


In [19]:
#Q2
# Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
arr4 = np.arange(1,10).reshape(3,3)
normalized = (arr4 - np.mean(arr4))/np.std(arr4)
print(normalized)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [21]:
# Assignment 5
# Q1
# Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
m = np.random.randint(1,10,size=(3,3))
n = np.random.randint(1,10,size=(3,))
print(m + n)

[[14 11  6]
 [ 9 18 10]
 [10 14  9]]


In [22]:
# Q2
# Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting
s = np.random.randint(1,10,size=(4,4))
t = np.random.randint(1,10,size=(4,))
print(s - t)

[[ 0 -5 -1  4]
 [ 1  2  5  2]
 [ 0  1  7  3]
 [ 0  3  3  2]]


In [2]:
# Assignment 6
# Q1
# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
s = np.random.randint(1,10,size=(3,3))
print("Matrix:")
print(s)
print("Determinant:")
print(np.linalg.det(s))
print("Inverse:")
print(np.linalg.inv(s))
print("Eigenvalues:")
print(np.linalg.eigvals(s)) 

Matrix:
[[5 4 5]
 [1 8 1]
 [6 9 3]]
Determinant:
-108.00000000000003
Inverse:
[[-0.13888889 -0.30555556  0.33333333]
 [-0.02777778  0.13888889  0.        ]
 [ 0.36111111  0.19444444 -0.33333333]]
Eigenvalues:
[-1.65564321 12.39138562  5.26425758]


In [4]:
# Q2
# Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
s = np.random.randint(1,10,size=(2,3))
t = np.random.randint(1,10,size=(3,2))
print("Matrix s:")
print(s)
print("Matrix t:")
print(t)
print("Matrix multiplication of s and t:")
print(np.dot(s,t))


Matrix s:
[[7 9 7]
 [1 2 5]]
Matrix t:
[[2 4]
 [4 5]
 [8 3]]
Matrix multiplication of s and t:
[[106  94]
 [ 50  29]]


In [5]:
# Assignment 7
# Q1
# Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.reshape(1,9))
print(a.reshape(9,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [6]:
# Q2
# Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
a = np.random.randint(1,100,size=(5,5))
print(a)
print(a.flatten())
print(a.flatten().reshape(5,5))

[[90 22  8 94 71]
 [51  2 45 24 22]
 [57 10 72 55 64]
 [17 21 17 50 63]
 [51 94 86 68 98]]
[90 22  8 94 71 51  2 45 24 22 57 10 72 55 64 17 21 17 50 63 51 94 86 68
 98]
[[90 22  8 94 71]
 [51  2 45 24 22]
 [57 10 72 55 64]
 [17 21 17 50 63]
 [51 94 86 68 98]]


In [7]:
# Assignment 8
# Q1
# Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
a = np.random.randint(1,100 , size = (5,5))
print(a)
print("Extracting the elements at the corners of the array:")
corners = [a[0][0], a[0][-1], a[-1][0], a[-1][-1]]
print(corners)

[[20 90 56 70  7]
 [87 30 71 37 41]
 [21 38 89 34 19]
 [70 84 66  5 26]
 [ 4 21 79 66 10]]
Extracting the elements at the corners of the array:
[20, 7, 4, 10]
